### ISSUE TITLE
Bug: eqMac crashed due to: "NSWindow drag regions should only be invalidated on the Main Thread!"

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#222]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Reported in #216 
eqMac crashed due to error: 
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
```

**Steps to Reproduce**
Could not reproduce my end. Waiting for users to report on what they did to cause such error to occur

**Setup information:**
_Waiting for users to report the fields below_
 - macOS Version: [e.g. 10.15]
 - eqMac Version [e.g. 0.0.1] **(if audio related issue)**

**Screenshots or Console.app logs**
Full crash dump from issue #216 
```
$ /Applications/eqMac.app/Contents/MacOS/eqMac
2020-04-17 09:44:43.753 eqMac[3488:47533] Sentry Started -- Version: 4.4.0
Error: 561211770 ->  /Users/romanskisils/Programming/Bitgapp/eqmac/native/app/Source/Audio/Sources/System/Driver.swift:68

Error: 561211770 ->  /Users/romanskisils/Programming/Bitgapp/eqmac/native/app/Source/Audio/Sources/System/Driver.swift:107

2020-04-17 09:44:47.106 eqMac[3488:47573] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3720cd07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6ff305bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3723550c -[NSException raise] + 9
	3   AppKit                              0x00007fff3443c24c -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff34423cb2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	5   AppKit                              0x00007fff34604a15 -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
	6   AppKit                              0x00007fff34423723 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	7   AppKit                              0x00007fff346049ca -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
	8   AppKit                              0x00007fff34421709 -[NSWindowTemplate nibInstantiate] + 393
	9   AppKit                              0x00007fff343ebaa6 -[NSIBObjectData instantiateObject:] + 253
	10  AppKit                              0x00007fff343eb160 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 534
	11  AppKit                              0x00007fff343df331 loadNib + 401
	12  AppKit                              0x00007fff343de8f2 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 693
	13  AppKit                              0x00007fff343de548 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	14  AppKit                              0x00007fff347a71c4 -[NSAlert init] + 101
	15  eqMac                               0x0000000107d62dc6 eqMac + 269766
	16  eqMac                               0x0000000107d62cba eqMac + 269498
	17  eqMac                               0x0000000107d27c14 eqMac + 27668
	18  eqMac                               0x0000000107d2798d eqMac + 27021
	19  eqMac                               0x0000000107d29e5b eqMac + 36443
	20  eqMac                               0x0000000107d2a4d9 eqMac + 38105
	21  eqMac                               0x0000000107d42660 eqMac + 136800
	22  libdispatch.dylib                   0x00007fff7107e658 _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x00007fff71080818 _dispatch_continuation_pop + 414
	24  libdispatch.dylib                   0x00007fff710904be _dispatch_source_invoke + 2084
	25  libdispatch.dylib                   0x00007fff71083af6 _dispatch_lane_serial_drain + 263
	26  libdispatch.dylib                   0x00007fff710845d6 _dispatch_lane_invoke + 363
	27  libdispatch.dylib                   0x00007fff7108dc09 _dispatch_workloop_worker_thread + 596
	28  libsystem_pthread.dylib             0x00007fff712d8a3d _pthread_wqthread + 290
	29  libsystem_pthread.dylib             0x00007fff712d7b77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    3488 abort      /Applications/eqMac.app/Contents/MacOS/eqMac
```

**Additional information**
Waiting for a chance to see the error happen to myself, also waiting for more info from users.

**Comment by fbcd4f50ea5350f051450323b5abfd0b** [comment]
Roman, I'm very sorry I caused unnecessary work.
After some searching I found the problem. The program LuLu (https://objective-see.com/products/lulu.html) had caused the problems and it had nothing to do with eqMac.

Sorry again!

**Comment by nodeful** [comment]
Well I think someone else reported this as well somewhere 😅 I will see if anyone else leaves any feedback and if not I will close this

**Comment by nodeful** [comment]
I will close this issue. Please comment on this issue if this error reoccurs. Thanks

**Comment by erikhuizinga** [comment]
Still an issue with eqMac 0.1.0 beta on macOS 10.14.6.

**Comment by nodeful** [comment]
Reported again in #256

**Comment by res88** [comment]
Still crashes everytime on startup with 0.1.1

Process:               eqMac [1073]
Path:                  /Applications/eqMac.app/Contents/MacOS/eqMac
Identifier:            com.bitgapp.eqmac
Version:               v0.1.1 (0.1.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           eqMac [1073]
User ID:               502

Date/Time:             2020-05-01 08:56:48.014 -0400
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)



Time Awake Since Boot: 1200 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: check-driver-shown

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff380bfd07 __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff70de35bf objc_exception_throw + 48
2   CoreFoundation                      0x00007fff380e850c -[NSException raise] + 9
3   AppKit                              0x00007fff352ef24c -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
4   AppKit                              0x00007fff352d6cb2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
5   AppKit                              0x00007fff354b7a15 -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
6   AppKit                              0x00007fff352d6723 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
7   AppKit                              0x00007fff354b79ca -[NSPanel initWithContentRect:styleMask:backing:defer:] + 64
8   AppKit                              0x00007fff352d4709 -[NSWindowTemplate nibInstantiate] + 393
9   AppKit                              0x00007fff3529eaa6 -[NSIBObjectData instantiateObject:] + 253
10  AppKit                              0x00007fff3529e160 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 534
11  AppKit                              0x00007fff35292331 loadNib + 401
12  AppKit                              0x00007fff352918f2 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 693
13  AppKit                              0x00007fff35291548 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
14  AppKit                              0x00007fff3565a1c4 -[NSAlert init] + 101
15  eqMac                               0x000000010e676826 eqMac + 268326
16  eqMac                               0x000000010e67673d eqMac + 268093
17  eqMac                               0x000000010e63b6c4 eqMac + 26308
18  eqMac                               0x000000010e63b432 eqMac + 25650
19  eqMac                               0x000000010e63d78b eqMac + 34699
20  eqMac                               0x000000010e6570a9 eqMac + 139433
21  libdispatch.dylib                   0x00007fff71f31658 _dispatch_client_callout + 8
22  libdispatch.dylib                   0x00007fff71f33818 _dispatch_continuation_pop + 414
23  libdispatch.dylib                   0x00007fff71f434be _dispatch_source_invoke + 2084
24  libdispatch.dylib                   0x00007fff71f36af6 _dispatch_lane_serial_drain + 263
25  libdispatch.dylib                   0x00007fff71f375d6 _dispatch_lane_invoke + 363
26  libdispatch.dylib                   0x00007fff71f40c09 _dispatch_workloop_worker_thread + 596
27  libsystem_pthread.dylib             0x00007fff7218ba3d _pthread_wqthread + 290
28  libsystem_pthread.dylib             0x00007fff7218ab77 start_wqthread + 15

**Comment by erikhuizinga** [comment]
For me too

**Comment by osmanlicilegi** [comment]
Same here with 0.1.1 on Catalina 10.15.4

[eqMac_2020-05-09-120131_Dincers-MacBook-Air.crash.zip](https://github.com/bitgapp/eqMac/files/4603083/eqMac_2020-05-09-120131_Dincers-MacBook-Air.crash.zip)

**Comment by nodeful** [comment]
Just release v0.2.0 please check if the issue still persists.
Download from [website](https://eqmac.app), [GitHub release](https://github.com/bitgapp/eqMac/releases/tag/v0.2.0) or update from within the app directly :)

**Comment by erikhuizinga** [comment]
v0.2.0 did start correctly for me, instead of immediately crashing, so that's progress. Let's await some hours of testing before concluding that this is fixed.

**Comment by nodeful** [comment]
I'm closing this issue for now as it's seems it's fine now as of v0.2 If that is not the case please tell me and I will reopen the issue

**Comment by nodeful** [comment]
Reopening as people have reported this problem still persisting even in v0.2.0

**Comment by ZyroBlue** [comment]
> Reopening as people have reported this problem still persisting even in v0.2.0

Sorry, my bad, I didn't know that I could reply to closed bugs. Very new to Github.

**Comment by ZyroBlue** [comment]
Well, I just got 10.15.5 and it works again. Sorry for bringing this up.

**Comment by kk7ds** [comment]
eqMac 0.2 was working fine for me until today, where it won't run. Starts up, I see the menu bar icon for a couple seconds, then it goes away. Here's what seems relevant from the crash log:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should
only be invalidated on the Main Thread!'
terminating with uncaught exception of type NSException
abort() called
```

**Comment by kk7ds** [comment]
I've also deleted everything in ~/Library with eqMac in the name and can't get it to come back to life. It also seems like maybe it's remembering stuff some other way, because it seems to still be starting up in menubar-only mode, which isn't the default, IIRC.

**Comment by nodeful** [comment]
Hey guys, can you please check if you have Microphone read access enabled in your System Preferences > Security & Privacy > Privacy tab > Microphone section > eqMac should be checked:
![image](https://user-images.githubusercontent.com/8472525/83302724-bdb37100-a1f3-11ea-8473-5501a89a07c5.png)
I've encountered the NSWindow drag issue when tried to disable access to the microphone!
eqMac needs access to the Microphone as that's how it reads the System Audio...

**Comment by kk7ds** [comment]
Yep, eqMac has microphone perms enabled on my system. BUT, if I disable it and then start eqMac, I get the "allow microphone permission?" dialog. I click "proceed" and eqMac crashes immediately. If I then approve it again and re-start eqmac, it loads and doesn't exit!

So, I think you're on to something there, even though it's more complicated than just not being permitted (according to the check box).

I'm on Mojave, by the way.

**Comment by nodeful** [comment]
I realised the underlying cause of why it's happening, but I'm not sure where is it happening from, if that makes sense. I will try to mitigate the underlying issue and also release a new version with Debug Symbols included, so the crash logs have more information I can use.

**Comment by kk7ds** [comment]
Cool, well, at least I have a workaround, so very much appreciate that. I'll be glad to run the version with symbols and re-report if I can reproduce it again.

**Comment by nodeful** [comment]
Can you please download pre-release version v0.2.1 from here: 
https://github.com/bitgapp/eqMac/releases/tag/v0.2.1
And test if this issue still persists.
Thanks

**Comment by kk7ds** [comment]
I get "unable to activate audio driver" when I start that version. I "try again" just causes it to exit. What am I doing wrong?

**Comment by Nitebreed** [comment]
I was having this issue on previous versions as well, and also as @kk7ds is saying v.0.2.1 shows 'Driver failed to activate' when starting up.

**Comment by erikhuizinga** [comment]
> I get "unable to activate audio driver" when I start that version. I "try again" just causes it to exit. What am I doing wrong?


> I was having this issue on previous versions as well, and also as @kk7ds is saying v.0.2.1 shows 'Driver failed to activate' when starting up.

That should be reported as a separate issue for this version. Possibly equal to #291, although that issue doesn't specify the app version. Report there.

**Comment by nodeful** [comment]
This issue should be resolved in [v0.3.1](https://github.com/bitgapp/eqMac/releases/tag/v0.3.1).
Please update the app and let me know if this issue is still relevant. Thank you
