### ISSUE TITLE
Bug: eqMac preventing Mac to go to sleep.

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#228]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Reported in #195 #34 #14

Most likely because the audio engine is running even when there's no audio playing and is still pumping sound (even though it's silent) the Mac thinks there's still some audio playing. But need to look into it a lot more.

**Expected behaviour**
If settings are set for the Mac to go to sleep after X amount of minutes, when there's nothing playing audio the Mac should go to sleep mode.

**Comment by nodeful** [comment]
I have done a bunch of testing and for me it seems to work as intended. If there's no audio playing then my laptop goes into sleep in 1 minute as set in settings here:
![image](https://user-images.githubusercontent.com/8472525/85286586-d0cffe80-b48a-11ea-8f12-151d124b22ce.png)
I will test with audio playing and report back. 
Would be helpful if people posted their Sleep settings and what state their machine is at the moment it should go to sleep (playing audio/video, device running audio through etc.)

**Comment by DesmondKong** [comment]
Thanks for looking into this. Loving eqMac! I think the issue happens only when audio is routed to HDMI or DisplayPort device. My laptop is connected via HDMI to my Dell monitor which is where my speakers are connected to. I was using Soundflower previously which had the [same issue](https://github.com/feniix/soundflower/issues/179).

![image](https://user-images.githubusercontent.com/34464274/85348984-4ba52200-b53c-11ea-8cbc-837651f1f550.png)

**Comment by slaysd** [comment]
Thanks for looking into this too. I have same environment with @DesmondKong.
My laptop is connected via DP to main monitor.

**Comment by adaugherity** [comment]
I can confirm that this not only prevents the system from sleeping, it also prevents the display from turning off (both the laptop screen and my external monitor).  I've been having this happen recently but not 100% of the time, and I think I've tracked it down to using DisplayPort audio with eqMac. If I switch eqMac to Internal Speakers, the display does sleep properly.  `pmset -g` reflects this:
```
% pmset -g
System-wide power settings:
Currently in use:
 standbydelaylow      4200
 standby              1
 womp                 1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 powernap             1
 networkoversleep     0
 disksleep            10
 standbydelayhigh     4200
 sleep                120 (sleep prevented by ProtectedCloudKeySyncing, coreaudiod, coreaudiod, cloudd, sharingd)
 autopoweroffdelay    28800
 hibernatemode        3
 autopoweroff         1
 ttyskeepawake        1
 displaysleep         10 (display sleep prevented by coreaudiod)
 highstandbythreshold 50
 acwake               0
 lidwake              1
```
_(This is with my MacBook Air on AC power; values are different on battery but still preventing display sleep.  I mainly use eqMac when connected to the external monitor, so I can control the DP audio volume.  The Dell 2408WFP likes to clip when the audio is too "hot", which sounds terrible, and it's also more convenient to use the volume up/down keys rather than the volume control on my speakers.)_

If I switch eqMac to internal speakers, the "display sleep prevented" message goes away.  I have to quit eqMac entirely to remove the two `coreaudiod` processes from the "sleep prevented" message, but I'm more concerned with display sleeping.

Note that using DP audio *without* eqMac only prevents the display sleeping when audio is playing, but when nothing is active, the monitor will go into power-save.   E.g. playing a YouTube video shows `displaysleep         10 (display sleep prevented by com.apple.WebKit.WebContent, coreaudiod)` in pmset; pause it and the webkit entry goes away, and a few seconds later, so does coreaudiod.  Looks like eqMac is always holding open an audio stream, which causes coreaudiod to keep the DP audio device active, preventing display sleep?

**Comment by specter78** [comment]
I am having the same issue.

Also, in my case, eqMac is constantly having current energy impact of **>3** even when there is **no** sound output / nothing is playing.

**Comment by greensouth** [comment]
Same here, connected via DP to an LG monitor with speakers. MacOS is unable to go to sleep when eqmac is opened.

**Comment by legendaryaman** [comment]
On DisplayPort audio, my mac won't go to sleep.

**Comment by artickc** [comment]
Same issue with hdmi :( no fixes?

**Comment by FTT2004** [comment]
Hi. To reduce duplicate entries I would like to report I am experiencing similar issues. 

pmset -g reveals
 coreaudiod, coreaudiod are preventing sleep. 

pmset -g assertions reveal:
pid 335(coreaudiod): [0x000005a00001812e] 00:23:22 PreventUserIdleSystemSleep named: "com.apple.audio.EQMDevice.context.preventuseridlesleep"  
	Created for PID: 654. 
   pid 335(coreaudiod): [0x000005a000018126] 00:23:22 PreventUserIdleSystemSleep named: "com.apple.audio.AppleHDAEngineOutput:1B,0,1,1:0.context.preventuseridlesleep"  

I initially checked Activity Monitor and I have a sample taken if you'd like me to send it? 

eqMac is set to internal speakers. Quitting and restarting the app displays a Yes under Preventing Sleep on Activity Monitor. 

Hope this is of some help. 

Thanks for everything you do. Since discovering the app it has changed how I listen to music.

**Comment by andretf** [comment]
App preventing sleep
: No HDMI or Bluetooth connection, sound interface: Mac internal Speakers

**Comment by nodeful** [comment]
I've just release a new PRE-Release v1.4.0 build that should solve this issue.
I'm looking for people to beta test this build.
You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.4.0 (eqMac.pkg)
Could you please try it out and report if this issue still persists or if there's any other issues.
Thank you! And sorry for the wait 🙏🏻

**Comment by DesmondKong** [comment]
> I've just release a new PRE-Release v1.4.0 build that should solve this issue. I'm looking for people to beta test this build. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.4.0 (eqMac.pkg) Could you please try it out and report if this issue still persists or if there's any other issues. Thank you! And sorry for the wait 🙏🏻

@nodeful , you nailed it! Seems to be working. No longer prevents sleep when nothing is playing. Will test further. Thanks!

**Comment by nodeful** [comment]
@DesmondKong thank you for confirming, I believe it indeed should be solved now, unless there's some background app that is piping silence to the system (which is also solvable would just require a bit more work on my side)

**Comment by nodeful** [comment]
Closing this issue as it was fixed in v1.4.0 and v1.6.2 is available to the entire user base. Thank you everyone for cooperation and your patience!

**Comment by jt3k** [comment]
[«eqMac».txt](https://github.com/bitgapp/eqMac/files/14158594/eqMac.txt)
this problem is back 
<img width="410" alt="image" src="https://github.com/bitgapp/eqMac/assets/1261240/24556d77-e1b6-41b1-8f9d-2763d9834c84">
<img width="669" alt="image" src="https://github.com/bitgapp/eqMac/assets/1261240/e66ebc81-764e-4436-a8bd-daa6cdd15ca7">

**Comment by KenDxD** [comment]
This problem is back on eqMac v1.8.7 on my MacBookPro14,2 only using speaker

**Comment by JJD2K** [comment]
Yes it is and it is awful. CPU usage goes up and mac heats up. I uninstalled - it's unusable now.
