### ISSUE TITLE
Bug: Not minimized on start

### ISSUE THREAD

**Issue by varg90** [bitgapp/eqMac#525]
**Describe the bug**
It doesn't minimize itself in status bar on system startup (using "Launch on start-up" setting and "Show Icon: Status Bar"). Worked correctly before the update 

**Steps to Reproduce**
Update to the version that is mentioned below, set "Launch on start-up" and restart the system. eqMac window will appear in the middle of the screen

**Expected behaviour**
eqMac launched and minimized on start-up

**Setup information:**
 - macOS Version: Big Sur 11.4
 - eqMac Version  1.0.0
 - eqMac UI Version 1.4.0
 - Driver Version 1.2.1
 
 **Additional information**
 There is no option to minimize it on the start-up so it would be much better to hide it by default since this is not what user needs when he starts his system
 
<img width="512" alt="Screenshot 2021-07-08 at 12 48 07" src="https://user-images.githubusercontent.com/2902480/124868972-c2e41180-dfea-11eb-8035-43c1b010a226.png">

<img width="512" alt="Screenshot 2021-07-08 at 12 47 28" src="https://user-images.githubusercontent.com/2902480/124868912-aea01480-dfea-11eb-9ccb-201db9e000ed.png">

**Comment by tcz305** [comment]
there are already several reports of this bug and the dev is aware of the issue, feel free to close this thread

**Comment by varg90** [comment]
Thanks for your answer, tried to find existing issues with "minimize" word and didn't find anything then started this one

**Comment by varg90** [comment]
In the `1.1.0` update notes there was a fix for this issue, but it is still not minimized on start. 
- UI Version 1.5.3
- App Version 1.1.0

**Comment by tcz305** [comment]
It is fixed in my case.
A solid blank white outline of the app first appears in the center of the screen, vanishes, and then appears under the menubar as I have it set in popover mode, and then closes, so while it does sort of appear, it then closes.

**Comment by varg90** [comment]
@tcz305 Thanks for your answer. I'll try to reinstall the app

**Comment by varg90** [comment]
Nope, reinstall didn't help in my case, still appears in the middle of the screen on startup

**Comment by tec-max** [comment]
same here, still not minimized on start.

Big Sur 26.07.2021, mac mini m1
UI Version 1.5.3
App Version 1.1.0

**Comment by varg90** [comment]
Not sure from what version, but it seems to be fixed in `App Version 1.3.1` `UI Version 3.0.6 (Remote)`
