### ISSUE TITLE
eqmac won't update audio driver.

### ISSUE THREAD

**Issue by whitty23** [bitgapp/eqMac#815]
Hi, first time posting on here so forgive me if this is in the wrong place. I've been using eqmac for a while now and it's worked really well for me. So thank you to the creator. Unfortunately,  Each time I've tried to update I've had an issue where it fails to update the audio capture driver. The first time this happened I was able to return to a previous version but this time the only version that will work is 1.0 that I found on an old thread on here. Nothing seems to be working. I've tried clearing old installs including any old audio drivers from eqmac 1/ 2 that may have installed a long the way. Any help would be much appreciated. I think I was on 1.74 and tried to install 1.77 when the issue arised. 
![Screenshot 2023-02-22 at 01 08 42](https://user-images.githubusercontent.com/126032882/220495952-8dcde34c-0434-4ecc-a990-cd29e5d598a0.png)

**Comment by Quicksur** [comment]
Same, it will not update the driver says failed to update. And it sounds like complete sh!t now, makes my Wharfdales Aiyima A07 sound like the whole system is blown with crackling garbled sound. Its fine on MacOs w/o EQ.

I've used Eq for over a year and loved it till now, what the heck happened? I even tried reusing previous update 1.4 or whatever it was and same (sounds like crap) reupdating to 1.7 it will not update driver needed.

**Comment by whitty23** [comment]
I've used version 1.0 tonight and that works just fine. I haven't had an issue with it sounding bad. Any other version just doesn't work at all so no sound unless I disable eqmac. Sound comes through fine otherwise. I use it so I don't have to manually turn my Yamaha mixer up and down on the faders all the time. I'll just keep using this version until I hear a fix has been made. It doesn't look as pretty but it does what I need atm.

**Comment by Sanvido** [comment]
I had a similar problem. I had to close all applications (I had amplitube and the browser on a youtube page). After closing all the programs, it updated the driver normally.

macos 12.6.3 (opencore patcher)

imac mid 2011

**Comment by Quicksur** [comment]
I downgraded to v1.0, different weird interface but it appears to be working, I think it even somehow recognized my settings from current version(s). Garbled and distorted sound is gone, but it seems to be like a notch or two not as good as what it was before this software hiccuped or whatever happened. 

May have to look at other options for EQ. I tried 1.7 again and it went to trash sounding like blown speakers and amp.

**Comment by whitty23** [comment]
> I had a similar problem. I had to close all applications (I had amplitube and the browser on a youtube page). After closing all the programs, it updated the driver normally.
> 
> macos 12.6.3 (opencore patcher)
> 
> imac mid 2011

Hi Sanvido, Thanks for the reply. I tried closing everything and still nothing unfortunately.

**Comment by whitty23** [comment]
> I downgraded to v1.0, different weird interface but it appears to be working, I think it even somehow recognized my settings from current version(s). Garbled and distorted sound is gone, but it seems to be like a notch or two not as good as what it was before this software hiccuped or whatever happened.
> 
> May have to look at other options for EQ. I tried 1.7 again and it went to trash sounding like blown speakers and amp.

Yeah, it's definitely not as good but it works, which is better than nothing atm. I'd be interested to hear if you find another that doesn't have an issue.

**Comment by nodeful** [comment]
Hey @whitty23 can we jump on a call so I can understand what is going on with the Driver install? 
If we can figure out why it's failing the install maybe we can fix the problem for everyone at once :)
Please reach out to me on contact@eqmac.app privately so we can establish a contact time.
For anyone in this thread, feel free to reach out as well so I can help you debug your issues as well!

**Comment by nodeful** [comment]
Hey there,
However is having issues with the Driver install, can you try to install this version and let me know if the driver is installing nicely:
https://github.com/bitgapp/eqMac/releases/tag/v1.7.8

Thank you

**Comment by phammond42** [comment]
Sadly, v1.7.8 hasn't fixed the driver install issue for me - I get the same error as the original poster, and it just loops around asking me to install the driver over and over.

**Comment by andsve** [comment]
Adding to the sample size; chiming in here as I updated to 1.7.8 today and could not install the driver, had to downgrade to 1.7.7 for it to work.

**Comment by macsrwe** [comment]
Me too. Quit the app, reopened, and it's claiming to be v1.7.7 and not giving me error messages anymore, so I'll wait on a fix.

**Comment by nodeful** [comment]
In v1.7.8 I added a logger and was able to gather some information on why it fails for some of you.
I'm now releasing v1.7.9 that should fix this hopefully, will let you know once it's available.

**Comment by nodeful** [comment]
Here's v1.7.9 that should not have the problem will the driver install 🤞🏻 
https://github.com/bitgapp/eqMac/releases/tag/v1.7.9

Please let me know how it goes

**Comment by whitty23** [comment]
Hi, sorry I haven't been in touch. I am very busy at work at the minute and haven't been checking personal emails etc. I've tried v1.79 but the issue still occurs for me :(. Is it possible that v1.0 is now causing a conflict? I have replaced it with the new app but getting the same message.

**Comment by nodeful** [comment]
Got a couple more logs with some errors, will release another fix.
Very annoying, trust me I know like no other, macOS just doesn't play ball

**Comment by nodeful** [comment]
What about this one @whitty23 
https://github.com/bitgapp/eqMac/releases/tag/v1.7.10

**Comment by realies** [comment]
Upgraded from 1.5.0. All versions in this issue thus far make eqMac go not responding with no window/dock icon present. Hovering over the speaker icon in the menu bar shows the spinning beach ball. macOS Ventura 13.2.1, MacBook Pro 14-inch, 2021.

**Comment by phammond42** [comment]
@nodeful fyi, v1.7.10 upgraded the driver just fine, using the in-app update approach. Thank you!

**Comment by Sanvido** [comment]
> > I had a similar problem. I had to close all applications (I had amplitube and the browser on a youtube page). After closing all the programs, it updated the driver normally.
> > macos 12.6.3 (opencore patcher)
> > imac mid 2011
> 
> Hi Sanvido, Thanks for the reply. I tried closing everything and still nothing unfortunately.

When you tried to update the diver, was the eqmac on enable or bypass? Please try to put it in bypass mode before updating the driver.

**Comment by whitty23** [comment]
Ok, so I've managed to install v1.10 BUT it now won't find any outputs. as you can see from the images below, I can select it in settings but I can't select anything in the main window. The drop down is now stuck on no output?
![Screenshot 2023-03-04 at 01 56 01](https://user-images.githubusercontent.com/126032882/222869627-6263d9da-9345-4186-b38
![Screenshot 2023-03-04 at 01 55 11](https://user-images.githubusercontent.com/126032882/222869634-c425ac43-551d-4945-ba4e-bb2a5d1a7397.png)
0-984886b2d868.png)

**Comment by whitty23** [comment]
@nodeful 
![Screenshot 2023-03-04 at 01 57 43](https://user-images.githubusercontent.com/126032882/222869708-32c38d3c-14c7-4714-9843-95512c78edb7.png)

**Comment by whitty23** [comment]
I've now had to completely uninstall eqmac as it was causing my Mac to crash. I'm now using the background music app so will see if that's stopped the crashing issue but it isn't as convenient as eqmac so hoping future releases will work better.

**Comment by Quicksur** [comment]
I managed to somehow get previous version to work and last version which wouldn't before. But it still sounded, crappy? Something is off. And I use an Aiyima amp for desktop. Just got another update notification and without thinking updated. Same error driver install, than  randomly it installed. But sound is still poor, especially bass/mid notes but treble has issues as well, makes it still sound sorta blown but like only a 1.4 as bad as previously when I had that issue. Without Aiyami sounds like a normal Mac and the amp connected to other devices works flawlessly.

I don't know whats going on with this EQ App. It was amazing since I've been using it, till recently.

**Comment by superjeng1** [comment]
Hi everyone, is this still happening? Please let me know if this is still happening by commenting or reach out to support on the bottom of the eqMac site. I would be looking into it. Thanks!

**Comment by whitty23** [comment]
I haven’t checked in a while but will do it later today and see if it works yet. If there hasn’t been another update since, I presume it’s still happening
