### ISSUE TITLE
Bug: Have to manually "reload" when changing the output device (after MacOS Sonoma update)

### ISSUE THREAD

**Issue by SebastianEShelby** [bitgapp/eqMac#870]
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When I switch the output device, eqMac no longer automatically recognizes the new output device which means the new output device's audio is no longer controlled by eqMac. This specially happens if the new output device is the monitor. 

The issue started happening after upgrading to MacOS Sonoma and was not there before that.

I now have to manually go to eqMac and press the "reload" icon next to the active output to force eqMac to gain back control of the audio device.

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Change audio output from MacOS menu bar.
2. eqMac will no longer control the new device's audio

**Expected behaviour**
eqMac should always control the volume of the active output device even after switching to a new output device using MacOS menu bar.

**Setup information:**
 - Audio device used for playback: speakers connected to usb-c monitor
 - Audio transmission interface: 3.5mm Jack
 - macOS Version: Sonoma 14.0
 - eqMac Version: 1.7.10

**Screenshots or Console.app logs**
N/A

**Additional information**
N/A

**Comment by golden07** [comment]
I have the same issue

**Comment by SebastianEShelby** [comment]
> I have the same issue

Can you test it again? It may have been resolved.

**Comment by pantone337cc** [comment]
> > I have the same issue
> 
> Can you test it again? It may have been resolved.

The same issue. We need new eqMac version

**Comment by golden07** [comment]
> > I have the same issue
> 
> Can you test it again? It may have been resolved.

i tested, had a fresh install of macos, and of eqMac, but de problem still exists.

**Comment by martinpelant** [comment]
I have the same issue with Sonoma on Mac Studio M2 & USB-C speakers

**Comment by rameezv** [comment]
Same issue here as well on a MBP Pro M1 Pro with my Bluetooth Headphones

**Comment by donie** [comment]
Same here, I noticed the repository haven't been updated for quite some time since it's seperate from the private build. Wondering if developer may aware of the issue or working on a fix?

**Comment by rodrigopaillan** [comment]
click on setting (gear icon on the bottom) on eqMac, on the new window uncheck the "Hide Driver device" that seems to fix the device name.

**Comment by kevinfales** [comment]
Bump; Same issue here. MBP running Sonoma (14.1.2) and Sony WH1000-XM5s via Bluetooth.

**Comment by ucabqll** [comment]
same issue, after awaking device, occasionally it stops overriding and have to manually quit and restart eqMac for overriding the audio output again.

**Comment by ArtRoman** [comment]
Same here, looks like driver is unloading on high memory usage, need to disable and reenable eqMac, reselect output device to make eqMac catch device, or just to restart eqMac

**Comment by ragauskl** [comment]
This should have been resolved in one of previous updates, can anyone confirm if this is still an issue?

**Comment by matthewlipski** [comment]
Still an issue for me, also affecting other panels (not just "Output" but also "Equalizers", etc) when you have auto-switching enabled for super profiles. I made a more thorough troubleshooting description in #732:

> I have 2 super profiles setup, "Headphones", which uses an EQ preset for my headphones, and "Speakers", which uses a flat EQ preset. I have these set to automatically switch when eqMac switches between the "External Speakers" and "MacBook Pro Speakers" outputs.
>
> When I plug/unplug headphones to/from the audio jack, the audio output automatically switches and I see the super profile in eqMac change accordingly, so the Super Profiles panel and auto-switching works fine. I can also hear that the EQ profiles are working properly for both profiles.
>
> However, despite this, the Equalizers panel doesn't change, and this is also true for the Output panel dropdown which still shows the old output and old active devices. Interestingly, after clicking the cog button in the Output panel, the menu which opens up actually does show the correct active devices unlike the dropdown.
>
> Right clicking the UI and clicking the "Reload" option forces the UI to update, and after doing that both the Equalizers and Output tabs display the correct settings for the active super profile.
>
> So really it seems like everything is working properly in the background, it's just parts of the UI aren't updating automatically and I have to use the "Reload" option to fix that.

**Comment by fastzombies** [comment]
I have a similar issue when joining a MS Teams meeting.  I always have to reload then reset.  This issue seems specific to Teams, I do not recall having this issue with other apps.
